name: IndexNow URL Submission

on:
  push:
    branches:
      - main  # Change this to 'master' if your default branch is master
    paths:
      - '**/*.html'  # Only triggers if an HTML file is added or changed

jobs:
  submit-to-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Send POST Request to Bing IndexNow
        run: |
          curl -X POST https://bing.com \
          -H "Content-Type: application/json; charset=utf-8" \
          -d '{
            "host": "yourcustomdomain.com",
            "key": "${{ secrets.INDEXNOW_KEY }}",
            "keyLocation": "https://www.nsccomputers.jo3.org{{secrets.INDEXNOW_KEY }}.txt",
            "urlList": [
              "https://www.nsccomputers.jo3.org/",
              "https://www.nsccomputers.jo3.org/aboutgp.html",
              "https://www.nsccomputers.jo3.org/nscgallery.html"
            ]
          }'
